### ISSUE TITLE
Got a push error

### ISSUE THREAD

**Issue by Huskydog9988** [helionmusic/rhinobot_heroku#10]
The error is " error: failed to push some refs to 'https://git.heroku.com/TheNameWouldBeHere.git' " I don't know what went wrong. I had git installed before I did this all, so maybe that's why. That's the best guess i can give. (I replaced the real name of the app with "TheNameWouldBeHere" for privacy reasons.)

**Comment by Huskydog9988** [comment]
No longer a error pushing and etc, “deploys” according to heroku but the bot doesn’t come online or even work for that matter.

**Comment by helionmusic** [comment]
Have you set the correct bot token and voice channels to auto-join in the config files?
