### ISSUE TITLE
ERROR: Sign in to confirm your age

### ISSUE THREAD

**Issue by Klish132** [helionmusic/rhinobot_heroku#103]
Getting this while trying to play an age-restricted video:

> ERROR: Sign in to confirm your age
> This video may be inappropriate for some users.
```

Error
Error extracting info from search string, youtubedl returned no data. You may need to restart the bot if this continues to happen.
```

Latest bot version. The requirements are up-to-date.

**Comment by helionmusic** [comment]
For issues with the actual music bot itself, you'll want to check on the bot's actual repository, we're only just setting it up in this repo to work on Heroku.

For your listed issue, it looks like it's been discussed here: https://github.com/Just-Some-Bots/MusicBot/issues/2220
Have a look and see if you can get it resolved

**Comment by Klish132** [comment]
Thank you, I fixed it!
1. Use an extension to make a cookies.txt file on youtube.com;
2. Put the cookies.txt file into "musicbot" folder;
3.  Open downloader.py and add 'cookiefile': 'cookies.txt' to the end of ytdl_format_options. Don't forget to add a comma after the last option ('usernetrc': True,);
4. Commit and push changes to heroku.

**How it should look like:**

![C__Users_Tuha9_Downloads_rhinobot_heroku_musicbot_downloader py - Notepad++_000090 17-09-2021](https://user-images.githubusercontent.com/43512312/133754786-1e11e189-8101-427d-89a8-1e160bf0e540.png)
