### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'fmt'

### ISSUE THREAD

**Issue by goenyan** [helionmusic/rhinobot_heroku#104]
**Describe the problem** 
sformatter = colorlog.LevelFormatter(
TypeError: __init__() missing 1 required positional argument: 'fmt'

**Steps to reproduce** 

**Expected behaviour** 
Bot not running

**Have you followed all the instructions?** 
- [x] Yes, I followed the instructions properly.

**Tried updating the dependencies?** 
- [x] Yes, they are up to date.
- [ ] Not applicable for this issue.

**Bot version** 
release-010620u

**Comment by codeinteger6** [comment]
Please use the updated requirements.txt file which will fix this problem.
