### ISSUE TITLE
Spotify did not work?

### ISSUE THREAD

**Issue by YuiyuD** [helionmusic/rhinobot_heroku#13]
Seem it downloading on youtube doesn't stream from Spotify?

**Comment by helionmusic** [comment]
To add spotify support, you have to follow these [instructions from the original bot makers](https://just-some-bots.github.io/MusicBot/using/spotify/) . There is a process where you have to request a Spotify development API key and add it to the bot, but it will only work with playing from Spotify URLs directly, I don't think it could search through to play songs.
