### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by That-One-dude** [helionmusic/rhinobot_heroku#2]
i get this error when i do git add .

error: open("AppData/Local/Comms/UnistoreDB/USS.jtx"): Permission denied
error: unable to index file AppData/Local/Comms/UnistoreDB/USS.jtx
fatal: adding files failed

**Comment by helionmusic** [comment]
I've just updated the bot and its files. Give it a shot now, it should work fine

**Comment by Musicbotaccount** [comment]
thanks!

**Comment by 911samuel** [comment]
i get this error when i do git add .

error: open("AppData/Local/Comms/UnistoreDB/USS.jtx"): Permission denied
error: unable to index file AppData/Local/Comms/UnistoreDB/USS.jtx
fatal: adding files failed
 
same question any help

**Comment by Maksasto** [comment]
error: open("AppData/Local/Comms/UnistoreDB/USS.jtx"): Permission denied
error: unable to index file 'AppData/Local/Comms/UnistoreDB/USS.jtx'
fatal: adding files failed
