### ISSUE TITLE
Music playback

### ISSUE THREAD

**Issue by destroyer19991** [helionmusic/rhinobot_heroku#20]
The bot wont stop playing music even when there is no one in the voice channel.

**Comment by codeinteger6** [comment]
Sorry for the late response. Have you set AutoPause to yes in your options.ini file?

**Comment by destroyer19991** [comment]
yes i do setup autopause to yes. Will try once more if issue remains will reply

**Comment by destroyer19991** [comment]
i think i set that to no working now but auto summon still dont work i have to summon the bot to voice channel

**Comment by codeinteger6** [comment]
Unfortunately the bot itself doesn't come with what you are talking about, the AutoSummon that is mentioned is to join the bot owner's connected voice channel when the bot is started.

**Comment by destroyer19991** [comment]
oh i see thanks for replying
