### ISSUE TITLE
Could not load an opus lib. 

### ISSUE THREAD

**Issue by Smixite** [helionmusic/rhinobot_heroku#21]
![Error](https://user-images.githubusercontent.com/45467260/60094420-913edb80-977e-11e9-9dc8-d80b5994f741.PNG)

**Comment by codeinteger6** [comment]
Did you add the [libopus buildpack](https://github.com/codeinteger6/heroku-buildpack-libopus.git)?

**Comment by codeinteger6** [comment]
I’m going to close this, please try to deploy the bot again following the instructions properly. If you continue to face difficulties, feel free to reopen this issue.
