### ISSUE TITLE
Bot token authentication error

### ISSUE THREAD

**Issue by Smixite** [helionmusic/rhinobot_heroku#24]
![image](https://user-images.githubusercontent.com/45467260/61168097-bdc66600-a57a-11e9-86f1-413693b61f10.png)

**Comment by codeinteger6** [comment]
Did you add your bot token in the options.ini file?

**Comment by Smixite** [comment]
Yes I did

**Comment by codeinteger6** [comment]
Make sure you put it in like this, where `thisismytoken` is your bot token.

![image](https://user-images.githubusercontent.com/44692189/61172186-bdda5c00-a5a2-11e9-888b-3c0dc3326097.png)

I highly recommend you use [Notepad++](https://notepad-plus-plus.org/download/v7.7.1.html) to edit the options.ini file.

**Comment by Smixite** [comment]
![image](https://user-images.githubusercontent.com/45467260/61172358-d43de300-a5b5-11e9-8fe9-6cebe901aefa.png)

**Comment by Smixite** [comment]
It shows up as bot_token

**Comment by codeinteger6** [comment]
Go to the Discord dev portal, copy the bot token and replace bot_token with the token you copied earlier in the options.ini file.

![image](https://user-images.githubusercontent.com/44692189/61172390-84572000-a5a5-11e9-98d4-75009a778530.png)

**Comment by Smixite** [comment]
Same issue despite editing with Notepad++

**Comment by codeinteger6** [comment]
Did you type the commands correctly in Git when deploying to Heroku?

**Comment by Smixite** [comment]
Yes all steps were followed

**Comment by Smixite** [comment]
I used it before in the past to deploy about two weeks ago it work

**Comment by Smixite** [comment]
Till now I tried again it didn't work

**Comment by codeinteger6** [comment]
I have just tried deploying a new bot to Heroku and I am not having any problems. I'm not sure why you're facing this problem if you followed the instructions properly.

Did you clone the repository or downloaded from the releases page?

**Comment by Smixite** [comment]
git clone 
\

**Comment by codeinteger6** [comment]
Please send a screenshot of your bot token in the options.ini file.

**Comment by Smixite** [comment]
![image](https://user-images.githubusercontent.com/45467260/61173515-04da4880-a5c7-11e9-8a16-67aee151d2f3.png)

**Comment by Smixite** [comment]
![image](https://user-images.githubusercontent.com/45467260/61173530-24717100-a5c7-11e9-9e91-097d46ba6627.png)

**Comment by codeinteger6** [comment]
I have deleted it so that no one can steal the token.

You have pasted it correctly, but it's not working. Can you try regenerating the bot token and putting it in the options.ini?

**Comment by Smixite** [comment]
Yea my token was regenerated the one I send u was invalid token

**Comment by codeinteger6** [comment]
Is the regenerated token working?

**Comment by Smixite** [comment]
Same issue

**Comment by codeinteger6** [comment]
I'm not sure what is happening then. Can't reproduce the issue so I have no idea. The only thing I can suggest is to redo everything again.

I will try and see what's causing the issue if possible when I have time.

**Comment by codeinteger6** [comment]
Can you try running the bot on your PC just to see if it's a Heroku related issue?

Follow the instructions given at https://just-some-bots.github.io/MusicBot/installing/windows/ and see if you get the same error. If you get the same error then it's a problem with the bot token.

**Comment by Smixite** [comment]
Same issue appearing running on windows

**Comment by codeinteger6** [comment]
Then this is a bot token issue. There isn't any problem with the bot.
There's nothing else I can suggest other than regenerate the token, deploy the bot on Heroku and see if it works.

**Comment by Smixite** [comment]
I tried using another discord account to generate token and the same issue

**Comment by enterv0id** [comment]
I'm having the same issue. No matter what I do, I've edited the options.ini, removed every example_ ini's, and when I check the options file on Heroku it's empty.
