### ISSUE TITLE
Summon command not working for default. 

### ISSUE THREAD

**Issue by TheFatalKiller** [helionmusic/rhinobot_heroku#28]
**Your question**
Whenever someone in the default category permission does !summon the bot replies with an error, I have tried fixing this in the permissions file but I cannot find an option saying summon or something stating that I can change the permission, so I’m wondering if there’s any way to give everyone the permission (default) to summon the bot. 

Another question (didn’t wanna open another issue) with the status option, if I put the status of the bot to something like `!help for help` will the status change to the song the bot is playing (when the bot is playing) and then return to the status that is currently set. Or will it just stay to what I set it to when the bot is playing a song. 

**Bot version**
The latest version with updated dependencies.

**Comment by codeinteger6** [comment]
Please let me know what the error message says.

**Comment by SnGmng** [comment]
Add "summon" to this line in your permissions.ini file.
https://github.com/helionmusic/rhinobot_heroku/blob/3c8e740758b49204dfb401c11ee6bb8011026cd0/config/permissions.ini#L106

**Comment by codeinteger6** [comment]
> Another question (didn’t wanna open another issue) with the status option, if I put the status of the bot to something like !help for help will the status change to the song the bot is playing (when the bot is playing) and then return to the status that is currently set. Or will it just stay to what I set it to when the bot is playing a song.

It won't show what song is playing if you set a custom status.
