### ISSUE TITLE
Aliases creation. 

### ISSUE THREAD

**Issue by TheFatalKiller** [helionmusic/rhinobot_heroku#29]
**Your question**
How do I make an alias in the Config folder, I have tried using the examples file but it did not work, I have made an aliases.json file with the aliases and it did not work and I also tried aliases.ini which didn’t give me errors but the aliases are still not created. 

Bot version: latest.

**Comment by codeinteger6** [comment]
Let's take whatever there is in the example_aliases.json file. You rename this file to aliases.json, then deploy the bot to Heroku. Then, for example (assuming if your prefix is !) you can use !p instead of !play.

You can add more commands in this list if needed.

**Comment by TheFatalKiller** [comment]
Once I rename it, it still gives an error.

**Comment by codeinteger6** [comment]
> Once I rename it, it still gives an error. And the : looks red.
> I’m trying to add my own aliases btw

May be a formatting issue. Can you copy and paste what is in your aliases.json file?

**Comment by TheFatalKiller** [comment]
Never mind sorry about this, it was a silly mistake I just forgot to put the comma.
