### ISSUE TITLE
Fail to play music

### ISSUE THREAD

**Issue by TheFatalKiller** [helionmusic/rhinobot_heroku#31]
**Describe the problem** 
- [ x] Yes, I followed the instructions properly.

**Tried updating the dependencies?** 
- [x ] Yes, they are up to date.
- [ ] Not applicable for this issue.

**Bot version** 
Latest

**Comment by codeinteger6** [comment]
Restart the bot in Heroku. This is YouTube trying to stop music Discord bots from using their service and has blocked some IPs. Restarting will usually fix it.

![image](https://user-images.githubusercontent.com/44692189/62026312-74be1500-b1fc-11e9-9a49-0dccf2ae7841.png)
