### ISSUE TITLE
Every song message and title doesn’t respond/appear with the song name. 

### ISSUE THREAD

**Issue by TheFatalKiller** [helionmusic/rhinobot_heroku#33]
**Describe the problem** 
So, whenever I play a song, the bot replies with “this song has been put in queue” but instead of showing the musics name like usual it started showing just a “_” and it’s the same for that status. 
**Have you followed all the instructions?** 
- [ x] Yes, I followed the instructions properly.

**Tried updating the dependencies?** 
- [ x] Yes, they are up to date.
- [ ] Not applicable for this issue.

**Bot version** 
Latest
![23773FE1-9C9F-4367-BB16-D27F0043E1DF](https://user-images.githubusercontent.com/47860911/62209583-e7142e00-b391-11e9-9fe4-fc8aad9f41f2.png)
![2A5BB1BC-44AB-419F-950C-C975616B5310](https://user-images.githubusercontent.com/47860911/62209584-e7142e00-b391-11e9-804b-61af28352774.png)

**Comment by codeinteger6** [comment]
This was fixed in youtube-dl version 2019.07.30, please follow the instructions given in the readme to update it.
