### ISSUE TITLE
Music won't play

### ISSUE THREAD

**Issue by Dennoquellovero** [helionmusic/rhinobot_heroku#38]
**Describe the problem**
Music won't start, also the indicator that shows if the bot is "speaking" stays green

**Have you followed all the instructions?**
- [X] Yes, I followed the instructions properly.

**Tried updating the dependencies?**
- [X] Yes, they are up to date.
- [ ] Not applicable for this issue.

latest

**Comment by codeinteger6** [comment]
Try changing the voice server region, Discord’s voice servers are overloaded right now due to the outbreak.

**Comment by Dennoquellovero** [comment]
It still doesn't work :(

**Comment by codeinteger6** [comment]
I have [updated the requirements.txt file](https://github.com/helionmusic/rhinobot_heroku/raw/master/requirements.txt). Can you use the new file and try again?

**Comment by Dennoquellovero** [comment]
Nothing changed

**Comment by codeinteger6** [comment]
Can you post the Heroku logs as the problem occurs?

**Comment by Dennoquellovero** [comment]
Sure
[tttestoh-logs.txt](https://github.com/helionmusic/rhinobot_heroku/files/4377890/tttestoh-logs-1585088022917.txt)

**Comment by codeinteger6** [comment]
Can you deploy the bot on Heroku again following the instructions? I think you may have missed a step. I tried deploying a new bot and it's working perfectly fine.

**Comment by Dennoquellovero** [comment]
It works fine now, mb
