### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by DiscordJS-ux** [helionmusic/rhinobot_heroku#39]
I followed the tuto to the letter and... my token doesn't seem to be working...
![image](https://user-images.githubusercontent.com/66149090/83319357-160f6080-a23e-11ea-80e8-bd615ad16523.png)
![image](https://user-images.githubusercontent.com/66149090/83319376-393a1000-a23e-11ea-822e-41b48b8a93eb.png)

**Comment by DiscordJS-ux** [comment]
And I've just tested locally on the pc, it works very well (identity config files).

**Comment by codeinteger6** [comment]
Can you try regenerating the token?

**Comment by codeinteger6** [comment]
I'm going to close this issue, feel free to reopen it if you are still experiencing problems
