### ISSUE TITLE
Save command not saving on git.

### ISSUE THREAD

**Issue by LegendModzYT** [helionmusic/rhinobot_heroku#43]
**Your question** 

> When adding songs to the autoplaylist using the {prefix}save command is there a way to get it to save that because as you know when it adds to the autoplaylist.txt on heroku it doesn't do it on git so it gets replaced by the one you have locally on your pc without the specified saved song. Is there any way to get it so if I were to save a song it would save to git and then I could do "git fetch" or "git pull" or any other way.

**Bot version** 
> MusicBot release-260819 Heroku Edition

**Comment by helionmusic** [comment]
Once you edit the file locally, you need to run `git add .` then `git commit -m "Update message"` and finally `git push heroku master` for it to push the changes to heroku

**Comment by LegendModzYT** [comment]
Yea so my question was is there a way to just have people save songs they like to the autoplaylist and then I could just do git fetch to update my local file?

**Comment by helionmusic** [comment]
Don't think so, best bet is to write a little script on your end to do this automation for you, maybe add it directly to the bot itself
