### ISSUE TITLE
Did everything correctly 

### ISSUE THREAD

**Issue by death-angel-141** [helionmusic/rhinobot_heroku#46]
![Capture](https://user-images.githubusercontent.com/61632737/87962958-a26b3080-cad5-11ea-8f8a-0f74bec930cd.PNG)
Everything was executed correctly in options.ini file but still the problem persists

**Comment by LegendModzYT** [comment]
Well your token seems to be invalid so try regenerating it and try it again.

**Comment by codeinteger6** [comment]
I am unable to reproduce the issue, however I have updated the bot to release-010620u, try it and see if it solves your issue.

Starting from this release, we have switched to the unofficial fork of the bot maintained by Team-JSB, which has a few developers from the original team and has been promoted in the official Discord support server. As this release contains several fixes as well as some new features, we recommend you update to this release. The fork will be updated regularly unlike the main repo.

To prevent any issues while updating, we strongly suggest you delete and recreate the Heroku application from scratch.
