### ISSUE TITLE
Bot not working anymore

### ISSUE THREAD

**Issue by SegwayJesus** [helionmusic/rhinobot_heroku#47]
Had no issues with the bot until sometime last night it just shut off, and I cant get it to work again, I even tried completely remaking the bot project and all on my computer and the bot doesnt come online.
I dont get any errors with the push or any of the commands it just doesnt come online after using the heroku ps:scale worker=1 command

**Comment by codeinteger6** [comment]
I have updated the bot to release-010620u, try it and see if it solves your issue.

Starting from this release, we have switched to the unofficial fork of the bot maintained by Team-JSB, which has a few developers from the original team and has been promoted in the official Discord support server. As this release contains several fixes as well as some new features, we recommend you update to this release. The fork will be updated regularly unlike the main repo.

To prevent any issues while updating, we strongly suggest you delete and recreate the Heroku application from scratch.
