### ISSUE TITLE
repeat function autosummon on play command and auto playlist queue. 

### ISSUE THREAD

**Issue by psychic-wolf** [helionmusic/rhinobot_heroku#63]
**Your question** 
can anyone update for song repeat function. it means if i repeat current song it will play repeatedly 
2nd thing is there any command to check auto play list songs ???

cant bot join channel with play command i mean there isnt need to summon then play 

**Bot version**  010620u

**Comment by codeinteger6** [comment]
Hello, we just modify the bot to work with Heroku, please direct feature requests to the original developers via [this link](https://github.com/Team-JSB/MusicBot/issues/new). Thanks
