### ISSUE TITLE
Disconnect Error

### ISSUE THREAD

**Issue by DogeTrigger** [helionmusic/rhinobot_heroku#7]
When I do "!disconnect" the bot doesn't disconnect. If you try to play music it will give you a error that the bot is not in the channel but it is and you basically can't summon the bot in any channel. So I have to keep restarting dyno everytime you want the bot to be disconnected. 

I followed all the instructions, restarted dyno and reinstalled the bot (deleted horku) (Extracted new files) and it still doesn't work. 

Screenshot of the logs
https://gyazo.com/980696287053e6afe76c4d43cfbe44ca

https://gyazo.com/88f78ac565d1a0f2095702c4bc3eea92

https://gyazo.com/d4bac71bb875b421ab4b4a405cc8a801

Screenshot of the bot still in VC
https://gyazo.com/208b70afc26bd9864aa27e92f3bbb7fc

**Comment by helionmusic** [comment]
This seems to be an error from the bot itself, have you checked there issues board from the actual bot’s page to see if anyone else has has this problem?

**Comment by helionmusic** [comment]
Seeing as I have not received a response in two weeks, and that the bot was just updated, I will consider this issue closed.
Feel free to reopen it if you need to.
